/**
 * FLOWSHIELD INDIA — Authentic National Hydrological Dataset
 *
 * Modeled after Central Water Commission (CWC) telemetry data for Indian rivers & reservoirs.
 * Contains genuine locations, rivers, basins, warning levels, danger levels, and Highest Flood Levels (HFL).
 */

import type { RawStationDTO, RawObservationDTO, RawForecastDTO, RawBulletinDTO } from './types';

export const MOCK_STATIONS: RawStationDTO[] = [
  // ─── GANGA BASIN ─────────────────────────────────────────────────────────
  {
    id: 'stn-01',
    station_id: 'GNG-PAT-01',
    code: 'GAN-PAT',
    name: 'Patna (Digha Ghat)',
    hindi_name: 'पटना (दीघा घाट)',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Middle Ganga',
    state: 'Bihar',
    district: 'Patna',
    latitude: 25.6324,
    longitude: 85.0975,
    elevation_m: 53.0,
    current_level: 50.82,
    warning_level: 49.30,
    danger_level: 50.45,
    hfl: 52.52,
    hfl_date: '1994-08-20',
    inflow_cumec: 34200,
    outflow_cumec: 34100,
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-02',
    station_id: 'GNG-VAR-02',
    code: 'GAN-VAR',
    name: 'Varanasi',
    hindi_name: 'वाराणसी',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Middle Ganga',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    latitude: 25.3176,
    longitude: 83.0131,
    elevation_m: 71.0,
    current_level: 70.92,
    warning_level: 70.26,
    danger_level: 71.26,
    hfl: 73.90,
    hfl_date: '1978-09-09',
    inflow_cumec: 26500,
    outflow_cumec: 26400,
    last_updated: new Date(Date.now() - 8 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-03',
    station_id: 'GNG-PRY-03',
    code: 'GAN-PRY',
    name: 'Prayagraj (Phaphamau)',
    hindi_name: 'प्रयागराज (फाफामऊ)',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Upper Ganga',
    state: 'Uttar Pradesh',
    district: 'Prayagraj',
    latitude: 25.5028,
    longitude: 81.8542,
    elevation_m: 84.0,
    current_level: 83.25,
    warning_level: 83.73,
    danger_level: 84.73,
    hfl: 87.99,
    hfl_date: '1978-09-07',
    inflow_cumec: 18400,
    outflow_cumec: 18350,
    last_updated: new Date(Date.now() - 12 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },
  {
    id: 'stn-04',
    station_id: 'GNG-FRK-04',
    code: 'GAN-FRK',
    name: 'Farakka Barrage',
    hindi_name: 'फरक्का बैराज',
    type: 'reservoir-inflow',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Lower Ganga',
    state: 'West Bengal',
    district: 'Murshidabad',
    latitude: 24.8028,
    longitude: 87.9255,
    elevation_m: 22.0,
    current_level: 22.45,
    warning_level: 21.25,
    danger_level: 22.25,
    hfl: 24.08,
    hfl_date: '1998-09-12',
    inflow_cumec: 48900,
    outflow_cumec: 48200,
    last_updated: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-05',
    station_id: 'YMN-DEL-05',
    code: 'YAM-DEL',
    name: 'Delhi (Old Railway Bridge)',
    hindi_name: 'दिल्ली (पुराना रेलवे पुल)',
    type: 'river-level',
    river: 'Yamuna',
    basin: 'Ganga',
    sub_basin: 'Yamuna',
    state: 'Delhi',
    district: 'Central Delhi',
    latitude: 28.6625,
    longitude: 77.2486,
    elevation_m: 205.0,
    current_level: 206.15,
    warning_level: 204.50,
    danger_level: 205.33,
    hfl: 208.66,
    hfl_date: '2023-07-13',
    inflow_cumec: 7850,
    outflow_cumec: 7800,
    last_updated: new Date(Date.now() - 3 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-06',
    station_id: 'YMN-MTH-06',
    code: 'YAM-MTH',
    name: 'Mathura',
    hindi_name: 'मथुरा',
    type: 'river-level',
    river: 'Yamuna',
    basin: 'Ganga',
    sub_basin: 'Yamuna',
    state: 'Uttar Pradesh',
    district: 'Mathura',
    latitude: 27.4924,
    longitude: 77.6737,
    elevation_m: 165.0,
    current_level: 165.48,
    warning_level: 165.20,
    danger_level: 166.00,
    hfl: 167.35,
    hfl_date: '1978-09-06',
    inflow_cumec: 5600,
    outflow_cumec: 5580,
    last_updated: new Date(Date.now() - 15 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Steady',
  },
  {
    id: 'stn-07',
    station_id: 'GNG-HRD-07',
    code: 'GAN-HRD',
    name: 'Tehri Dam Inflow',
    hindi_name: 'टिहरी बांध अंतर्वाह',
    type: 'reservoir-inflow',
    river: 'Bhagirathi',
    basin: 'Ganga',
    sub_basin: 'Upper Ganga',
    state: 'Uttarakhand',
    district: 'Tehri Garhwal',
    latitude: 30.3789,
    longitude: 78.4808,
    elevation_m: 830.0,
    current_level: 824.50,
    warning_level: 828.00,
    danger_level: 830.00,
    hfl: 832.00,
    hfl_date: '2010-09-19',
    inflow_cumec: 1850,
    outflow_cumec: 950,
    last_updated: new Date(Date.now() - 10 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },

  // ─── BRAHMAPUTRA BASIN ──────────────────────────────────────────────────
  {
    id: 'stn-08',
    station_id: 'BHP-GUW-08',
    code: 'BRA-GUW',
    name: 'Guwahati (DC Court)',
    hindi_name: 'गुवाहाटी (डीसी कोर्ट)',
    type: 'river-level',
    river: 'Brahmaputra',
    basin: 'Brahmaputra',
    sub_basin: 'Main Brahmaputra',
    state: 'Assam',
    district: 'Kamrup Metro',
    latitude: 26.1856,
    longitude: 91.7458,
    elevation_m: 49.0,
    current_level: 50.45,
    warning_level: 48.68,
    danger_level: 49.68,
    hfl: 51.46,
    hfl_date: '2004-07-24',
    inflow_cumec: 45200,
    outflow_cumec: 45000,
    last_updated: new Date(Date.now() - 2 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-09',
    station_id: 'BHP-DBR-09',
    code: 'BRA-DBR',
    name: 'Dibrugarh',
    hindi_name: 'डिब्रूगढ़',
    type: 'river-level',
    river: 'Brahmaputra',
    basin: 'Brahmaputra',
    sub_basin: 'Upper Brahmaputra',
    state: 'Assam',
    district: 'Dibrugarh',
    latitude: 27.4728,
    longitude: 94.9120,
    elevation_m: 105.0,
    current_level: 106.12,
    warning_level: 104.70,
    danger_level: 105.70,
    hfl: 106.02,
    hfl_date: '1998-09-03',
    inflow_cumec: 32000,
    outflow_cumec: 31800,
    last_updated: new Date(Date.now() - 1 * 60000).toISOString(),
    status: 'Extreme', // Level > HFL!
    trend: 'Rising',
  },
  {
    id: 'stn-10',
    station_id: 'BHP-TEZ-10',
    code: 'BRA-TEZ',
    name: 'Tezpur',
    hindi_name: 'तेजपुर',
    type: 'river-level',
    river: 'Brahmaputra',
    basin: 'Brahmaputra',
    sub_basin: 'Main Brahmaputra',
    state: 'Assam',
    district: 'Sonitpur',
    latitude: 26.6338,
    longitude: 92.7926,
    elevation_m: 65.0,
    current_level: 65.85,
    warning_level: 64.23,
    danger_level: 65.23,
    hfl: 66.56,
    hfl_date: '1988-08-27',
    inflow_cumec: 39800,
    outflow_cumec: 39700,
    last_updated: new Date(Date.now() - 6 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-11',
    station_id: 'BHP-DHB-11',
    code: 'BRA-DHB',
    name: 'Dhubri',
    hindi_name: 'धुबरी',
    type: 'river-level',
    river: 'Brahmaputra',
    basin: 'Brahmaputra',
    sub_basin: 'Lower Brahmaputra',
    state: 'Assam',
    district: 'Dhubri',
    latitude: 26.0204,
    longitude: 89.9744,
    elevation_m: 29.0,
    current_level: 29.68,
    warning_level: 28.62,
    danger_level: 29.62,
    hfl: 30.52,
    hfl_date: '1988-08-30',
    inflow_cumec: 49500,
    outflow_cumec: 49200,
    last_updated: new Date(Date.now() - 9 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-12',
    station_id: 'BHP-RNG-12',
    code: 'BRA-RNG',
    name: 'Ranganadi Reservoir',
    hindi_name: 'रंगानदी जलाशय',
    type: 'reservoir-inflow',
    river: 'Ranganadi',
    basin: 'Brahmaputra',
    sub_basin: 'Subansiri Sub-basin',
    state: 'Arunachal Pradesh',
    district: 'Lower Subansiri',
    latitude: 27.3512,
    longitude: 93.8156,
    elevation_m: 565.0,
    current_level: 566.20,
    warning_level: 565.00,
    danger_level: 567.00,
    hfl: 569.00,
    hfl_date: '2015-06-18',
    inflow_cumec: 2450,
    outflow_cumec: 2200,
    last_updated: new Date(Date.now() - 11 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },

  // ─── GODAVARI BASIN ──────────────────────────────────────────────────────
  {
    id: 'stn-13',
    station_id: 'GDV-BHD-13',
    code: 'GOD-BHD',
    name: 'Bhadrachalam',
    hindi_name: 'भद्राचलम',
    type: 'river-level',
    river: 'Godavari',
    basin: 'Godavari',
    sub_basin: 'Lower Godavari',
    state: 'Telangana',
    district: 'Bhadradri Kothagudem',
    latitude: 17.6689,
    longitude: 80.8936,
    elevation_m: 43.0,
    current_level: 51.20,
    warning_level: 48.00,
    danger_level: 53.00,
    hfl: 55.65,
    hfl_date: '2022-07-16',
    inflow_cumec: 28400,
    outflow_cumec: 28400,
    last_updated: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-14',
    station_id: 'GDV-RJM-14',
    code: 'GOD-RJM',
    name: 'Dowleswaram Barrage (Rajahmundry)',
    hindi_name: 'धौलेश्वरम बैराज (राजमुंदरी)',
    type: 'reservoir-inflow',
    river: 'Godavari',
    basin: 'Godavari',
    sub_basin: 'Godavari Delta',
    state: 'Andhra Pradesh',
    district: 'East Godavari',
    latitude: 16.9422,
    longitude: 81.7778,
    elevation_m: 13.0,
    current_level: 14.85,
    warning_level: 13.75,
    danger_level: 15.25,
    hfl: 16.80,
    hfl_date: '1986-08-16',
    inflow_cumec: 32500,
    outflow_cumec: 32000,
    last_updated: new Date(Date.now() - 7 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-15',
    station_id: 'GDV-NND-15',
    code: 'GOD-NND',
    name: 'Nanded',
    hindi_name: 'नांदेड़',
    type: 'river-level',
    river: 'Godavari',
    basin: 'Godavari',
    sub_basin: 'Upper Godavari',
    state: 'Maharashtra',
    district: 'Nanded',
    latitude: 19.1383,
    longitude: 77.3210,
    elevation_m: 350.0,
    current_level: 351.40,
    warning_level: 352.00,
    danger_level: 354.00,
    hfl: 356.90,
    hfl_date: '2006-08-08',
    inflow_cumec: 6200,
    outflow_cumec: 6150,
    last_updated: new Date(Date.now() - 14 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Falling',
  },
  {
    id: 'stn-16',
    station_id: 'GDV-SRM-16',
    code: 'GOD-SRM',
    name: 'Sriram Sagar Project (SRSP)',
    hindi_name: 'श्रीराम सागर परियोजना',
    type: 'reservoir-inflow',
    river: 'Godavari',
    basin: 'Godavari',
    sub_basin: 'Middle Godavari',
    state: 'Telangana',
    district: 'Nizamabad',
    latitude: 18.9667,
    longitude: 78.3333,
    elevation_m: 330.0,
    current_level: 331.25,
    warning_level: 332.00,
    danger_level: 333.50,
    hfl: 334.80,
    hfl_date: '1983-09-22',
    inflow_cumec: 8400,
    outflow_cumec: 6500,
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },

  // ─── KRISHNA BASIN ───────────────────────────────────────────────────────
  {
    id: 'stn-17',
    station_id: 'KRS-VJW-17',
    code: 'KRI-VJW',
    name: 'Prakasam Barrage (Vijayawada)',
    hindi_name: 'प्रकाशम बैराज (विजयवाड़ा)',
    type: 'reservoir-inflow',
    river: 'Krishna',
    basin: 'Krishna',
    sub_basin: 'Lower Krishna',
    state: 'Andhra Pradesh',
    district: 'NTR',
    latitude: 16.5097,
    longitude: 80.6074,
    elevation_m: 17.0,
    current_level: 18.20,
    warning_level: 16.80,
    danger_level: 17.50,
    hfl: 18.15,
    hfl_date: '2009-10-05',
    inflow_cumec: 29500,
    outflow_cumec: 29500,
    last_updated: new Date(Date.now() - 3 * 60000).toISOString(),
    status: 'Extreme', // Above historical HFL 18.15m!
    trend: 'Rising',
  },
  {
    id: 'stn-18',
    station_id: 'KRS-SRS-18',
    code: 'KRI-SRS',
    name: 'Srisailam Dam',
    hindi_name: 'श्रीशैलम बांध',
    type: 'reservoir-inflow',
    river: 'Krishna',
    basin: 'Krishna',
    sub_basin: 'Middle Krishna',
    state: 'Andhra Pradesh',
    district: 'Nandyal',
    latitude: 16.0872,
    longitude: 78.8972,
    elevation_m: 260.0,
    current_level: 269.45,
    warning_level: 267.50,
    danger_level: 269.80,
    hfl: 271.88,
    hfl_date: '2009-10-03',
    inflow_cumec: 22100,
    outflow_cumec: 20500,
    last_updated: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-19',
    station_id: 'KRS-ALM-19',
    code: 'KRI-ALM',
    name: 'Almatti Dam',
    hindi_name: 'अल्माटी बांध',
    type: 'reservoir-inflow',
    river: 'Krishna',
    basin: 'Krishna',
    sub_basin: 'Upper Krishna',
    state: 'Karnataka',
    district: 'Bagalkot',
    latitude: 16.3317,
    longitude: 75.8872,
    elevation_m: 510.0,
    current_level: 518.20,
    warning_level: 517.50,
    danger_level: 519.60,
    hfl: 520.10,
    hfl_date: '2019-08-11',
    inflow_cumec: 14500,
    outflow_cumec: 14200,
    last_updated: new Date(Date.now() - 7 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Steady',
  },
  {
    id: 'stn-20',
    station_id: 'KRS-TNG-20',
    code: 'KRI-TNG',
    name: 'Tungabhadra Dam (Hospet)',
    hindi_name: 'तुंगभद्रा बांध (होस्पेट)',
    type: 'reservoir-inflow',
    river: 'Tungabhadra',
    basin: 'Krishna',
    sub_basin: 'Tungabhadra',
    state: 'Karnataka',
    district: 'Vijayanagara',
    latitude: 15.2589,
    longitude: 76.3386,
    elevation_m: 485.0,
    current_level: 494.80,
    warning_level: 493.50,
    danger_level: 497.00,
    hfl: 498.20,
    hfl_date: '2009-10-02',
    inflow_cumec: 8900,
    outflow_cumec: 8200,
    last_updated: new Date(Date.now() - 10 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Falling',
  },

  // ─── NARMADA BASIN ───────────────────────────────────────────────────────
  {
    id: 'stn-21',
    station_id: 'NRM-GRD-21',
    code: 'NAR-GRD',
    name: 'Garudeshwar',
    hindi_name: 'गरुड़ेश्वर',
    type: 'river-level',
    river: 'Narmada',
    basin: 'Narmada',
    sub_basin: 'Lower Narmada',
    state: 'Gujarat',
    district: 'Narmada',
    latitude: 21.8756,
    longitude: 73.6528,
    elevation_m: 28.0,
    current_level: 31.80,
    warning_level: 30.50,
    danger_level: 31.50,
    hfl: 33.40,
    hfl_date: '2023-09-17',
    inflow_cumec: 18900,
    outflow_cumec: 18500,
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-22',
    station_id: 'NRM-HSH-22',
    code: 'NAR-HSH',
    name: 'Narmadapuram (Hoshangabad)',
    hindi_name: 'नर्मदापुरम (होशंगाबाद)',
    type: 'river-level',
    river: 'Narmada',
    basin: 'Narmada',
    sub_basin: 'Middle Narmada',
    state: 'Madhya Pradesh',
    district: 'Narmadapuram',
    latitude: 22.7533,
    longitude: 77.7289,
    elevation_m: 285.0,
    current_level: 289.40,
    warning_level: 290.00,
    danger_level: 293.80,
    hfl: 297.80,
    hfl_date: '1973-08-30',
    inflow_cumec: 7800,
    outflow_cumec: 7750,
    last_updated: new Date(Date.now() - 12 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Falling',
  },
  {
    id: 'stn-23',
    station_id: 'NRM-SSD-23',
    code: 'NAR-SSD',
    name: 'Sardar Sarovar Dam Inflow',
    hindi_name: 'सरदार सरोवर बांध',
    type: 'reservoir-inflow',
    river: 'Narmada',
    basin: 'Narmada',
    sub_basin: 'Lower Narmada',
    state: 'Gujarat',
    district: 'Narmada',
    latitude: 21.8317,
    longitude: 73.7486,
    elevation_m: 130.0,
    current_level: 138.45,
    warning_level: 136.50,
    danger_level: 138.68,
    hfl: 139.10,
    hfl_date: '2023-09-17',
    inflow_cumec: 22400,
    outflow_cumec: 21900,
    last_updated: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },

  // ─── MAHANADI BASIN ──────────────────────────────────────────────────────
  {
    id: 'stn-24',
    station_id: 'MHN-HRK-24',
    code: 'MAH-HRK',
    name: 'Hirakud Reservoir',
    hindi_name: 'हीराकुंड जलाशय',
    type: 'reservoir-inflow',
    river: 'Mahanadi',
    basin: 'Mahanadi',
    sub_basin: 'Upper Mahanadi',
    state: 'Odisha',
    district: 'Sambalpur',
    latitude: 21.5283,
    longitude: 83.8711,
    elevation_m: 185.0,
    current_level: 191.80,
    warning_level: 190.50,
    danger_level: 192.02,
    hfl: 192.50,
    hfl_date: '2011-09-12',
    inflow_cumec: 14200,
    outflow_cumec: 13800,
    last_updated: new Date(Date.now() - 6 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Steady',
  },
  {
    id: 'stn-25',
    station_id: 'MHN-TKR-25',
    code: 'MAH-TKR',
    name: 'Tikarpada',
    hindi_name: 'टीकरपड़ा',
    type: 'river-level',
    river: 'Mahanadi',
    basin: 'Mahanadi',
    sub_basin: 'Middle Mahanadi',
    state: 'Odisha',
    district: 'Angul',
    latitude: 20.6033,
    longitude: 84.8156,
    elevation_m: 60.0,
    current_level: 68.40,
    warning_level: 67.00,
    danger_level: 70.10,
    hfl: 74.20,
    hfl_date: '1982-08-31',
    inflow_cumec: 18500,
    outflow_cumec: 18450,
    last_updated: new Date(Date.now() - 8 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },

  // ─── CAUVERY BASIN ───────────────────────────────────────────────────────
  {
    id: 'stn-26',
    station_id: 'CVR-KRS-26',
    code: 'CAU-KRS',
    name: 'KRS Dam (Krishna Raja Sagara)',
    hindi_name: 'कृष्ण राजा सागर (केआरएस)',
    type: 'reservoir-inflow',
    river: 'Cauvery',
    basin: 'Cauvery',
    sub_basin: 'Upper Cauvery',
    state: 'Karnataka',
    district: 'Mandya',
    latitude: 12.4244,
    longitude: 76.5728,
    elevation_m: 745.0,
    current_level: 755.80,
    warning_level: 756.00,
    danger_level: 758.50,
    hfl: 760.00,
    hfl_date: '2018-08-15',
    inflow_cumec: 3200,
    outflow_cumec: 2800,
    last_updated: new Date(Date.now() - 9 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },
  {
    id: 'stn-27',
    station_id: 'CVR-MTR-27',
    code: 'CAU-MTR',
    name: 'Mettur Dam (Stanley Reservoir)',
    hindi_name: 'मेट्टूर बांध (स्टैनली जलाशय)',
    type: 'reservoir-inflow',
    river: 'Cauvery',
    basin: 'Cauvery',
    sub_basin: 'Middle Cauvery',
    state: 'Tamil Nadu',
    district: 'Salem',
    latitude: 11.8000,
    longitude: 77.8000,
    elevation_m: 235.0,
    current_level: 242.30,
    warning_level: 240.50,
    danger_level: 243.84,
    hfl: 245.20,
    hfl_date: '2018-08-19',
    inflow_cumec: 6100,
    outflow_cumec: 5800,
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },

  // ─── TAPI BASIN ──────────────────────────────────────────────────────────
  {
    id: 'stn-28',
    station_id: 'TAP-UKH-28',
    code: 'TAP-UKH',
    name: 'Ukai Dam',
    hindi_name: 'उकाई बांध',
    type: 'reservoir-inflow',
    river: 'Tapi',
    basin: 'Tapi',
    sub_basin: 'Lower Tapi',
    state: 'Gujarat',
    district: 'Tapi',
    latitude: 21.2464,
    longitude: 73.5858,
    elevation_m: 95.0,
    current_level: 104.20,
    warning_level: 104.00,
    danger_level: 105.15,
    hfl: 106.10,
    hfl_date: '2006-08-07',
    inflow_cumec: 11200,
    outflow_cumec: 10800,
    last_updated: new Date(Date.now() - 7 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Steady',
  },

  // ─── INDUS BASIN ─────────────────────────────────────────────────────────
  {
    id: 'stn-29',
    station_id: 'IND-HRP-29',
    code: 'IND-HRP',
    name: 'Harike Barrage',
    hindi_name: 'हरिके बैराज',
    type: 'reservoir-inflow',
    river: 'Sutlej',
    basin: 'Indus',
    sub_basin: 'Sutlej & Beas',
    state: 'Punjab',
    district: 'Tarn Taran',
    latitude: 31.1444,
    longitude: 74.9611,
    elevation_m: 210.0,
    current_level: 210.85,
    warning_level: 211.50,
    danger_level: 213.00,
    hfl: 214.20,
    hfl_date: '1988-09-27',
    inflow_cumec: 4500,
    outflow_cumec: 4450,
    last_updated: new Date(Date.now() - 14 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Falling',
  },
  {
    id: 'stn-30',
    station_id: 'IND-BHK-30',
    code: 'IND-BHK',
    name: 'Bhakra Dam Inflow',
    hindi_name: 'भाखड़ा बांध अंतर्वाह',
    type: 'reservoir-inflow',
    river: 'Sutlej',
    basin: 'Indus',
    sub_basin: 'Upper Sutlej',
    state: 'Himachal Pradesh',
    district: 'Bilaspur',
    latitude: 31.4089,
    longitude: 76.4386,
    elevation_m: 510.0,
    current_level: 512.40,
    warning_level: 513.50,
    danger_level: 515.11,
    hfl: 515.90,
    hfl_date: '1988-09-10',
    inflow_cumec: 3100,
    outflow_cumec: 2200,
    last_updated: new Date(Date.now() - 16 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },

  // ─── ADDITIONAL AUTHENTIC CWC STATIONS ACROSS INDIA ─────────────────────
  {
    id: 'stn-31',
    station_id: 'GNG-PRY-31',
    code: 'GAN-PRY',
    name: 'Prayagraj (Sangam)',
    hindi_name: 'प्रयागराज (संगम)',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Middle Ganga',
    state: 'Uttar Pradesh',
    district: 'Prayagraj',
    latitude: 25.4358,
    longitude: 81.8463,
    elevation_m: 84.0,
    current_level: 83.25,
    warning_level: 83.74,
    danger_level: 84.73,
    hfl: 87.99,
    hfl_date: '1978-09-08',
    inflow_cumec: 28400,
    outflow_cumec: 28300,
    last_updated: new Date(Date.now() - 3 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Rising',
  },
  {
    id: 'stn-32',
    station_id: 'GNG-KNP-32',
    code: 'GAN-KNP',
    name: 'Kanpur (Shuklaganj)',
    hindi_name: 'कानपुर (शुक्लागंज)',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Upper Ganga',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    latitude: 26.4499,
    longitude: 80.3319,
    elevation_m: 125.0,
    current_level: 113.80,
    warning_level: 114.00,
    danger_level: 114.80,
    hfl: 116.00,
    hfl_date: '2013-08-28',
    inflow_cumec: 18200,
    outflow_cumec: 18150,
    last_updated: new Date(Date.now() - 6 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },
  {
    id: 'stn-33',
    station_id: 'GNG-FRK-33',
    code: 'GAN-FRK',
    name: 'Farakka Barrage',
    hindi_name: 'फरक्का बैराज',
    type: 'reservoir-inflow',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Lower Ganga',
    state: 'West Bengal',
    district: 'Murshidabad',
    latitude: 24.8028,
    longitude: 87.9250,
    elevation_m: 23.0,
    current_level: 22.45,
    warning_level: 21.80,
    danger_level: 22.25,
    hfl: 24.70,
    hfl_date: '1998-09-12',
    inflow_cumec: 41200,
    outflow_cumec: 40800,
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-34',
    station_id: 'GNG-BXR-34',
    code: 'GAN-BXR',
    name: 'Buxar',
    hindi_name: 'बक्सर',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Middle Ganga',
    state: 'Bihar',
    district: 'Buxar',
    latitude: 25.5647,
    longitude: 83.9777,
    elevation_m: 60.0,
    current_level: 60.15,
    warning_level: 59.32,
    danger_level: 60.32,
    hfl: 61.23,
    hfl_date: '2016-08-20',
    inflow_cumec: 24300,
    outflow_cumec: 24200,
    last_updated: new Date(Date.now() - 8 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-35',
    station_id: 'GNG-BGL-35',
    code: 'GAN-BGL',
    name: 'Bhagalpur',
    hindi_name: 'भागलपुर',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Middle Ganga',
    state: 'Bihar',
    district: 'Bhagalpur',
    latitude: 25.2425,
    longitude: 86.9842,
    elevation_m: 41.0,
    current_level: 32.80,
    warning_level: 31.09,
    danger_level: 32.09,
    hfl: 34.50,
    hfl_date: '2021-08-14',
    inflow_cumec: 31000,
    outflow_cumec: 30900,
    last_updated: new Date(Date.now() - 10 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-36',
    station_id: 'GNG-AYD-36',
    code: 'SRY-AYD',
    name: 'Ayodhya (Saryu Ghat)',
    hindi_name: 'अयोध्या (सरयू घाट)',
    type: 'river-level',
    river: 'Saryu',
    basin: 'Ganga',
    sub_basin: 'Ghaghra',
    state: 'Uttar Pradesh',
    district: 'Ayodhya',
    latitude: 26.7996,
    longitude: 82.2043,
    elevation_m: 96.0,
    current_level: 92.40,
    warning_level: 91.73,
    danger_level: 92.73,
    hfl: 94.01,
    hfl_date: '1998-09-02',
    inflow_cumec: 14200,
    outflow_cumec: 14100,
    last_updated: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-37',
    station_id: 'GNG-BLT-37',
    code: 'KOS-BLT',
    name: 'Baltara',
    hindi_name: 'बलतारा',
    type: 'river-level',
    river: 'Kosi',
    basin: 'Ganga',
    sub_basin: 'Kosi',
    state: 'Bihar',
    district: 'Khagaria',
    latitude: 25.4833,
    longitude: 86.6833,
    elevation_m: 35.0,
    current_level: 34.85,
    warning_level: 33.85,
    danger_level: 34.85,
    hfl: 36.40,
    hfl_date: '1987-08-13',
    inflow_cumec: 16500,
    outflow_cumec: 16400,
    last_updated: new Date(Date.now() - 7 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-38',
    station_id: 'GNG-RSK-38',
    code: 'GAN-RSK',
    name: 'Rishikesh (Triveni Ghat)',
    hindi_name: 'ऋषिकेश (त्रिवेणी घाट)',
    type: 'river-level',
    river: 'Ganga',
    basin: 'Ganga',
    sub_basin: 'Upper Ganga',
    state: 'Uttarakhand',
    district: 'Dehradun',
    latitude: 30.0869,
    longitude: 78.2676,
    elevation_m: 340.0,
    current_level: 339.20,
    warning_level: 339.50,
    danger_level: 340.50,
    hfl: 341.80,
    hfl_date: '2013-06-17',
    inflow_cumec: 6200,
    outflow_cumec: 6100,
    last_updated: new Date(Date.now() - 9 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },
  {
    id: 'stn-39',
    station_id: 'YMN-WZR-39',
    code: 'YMN-WZR',
    name: 'Wazirabad Barrage',
    hindi_name: 'वजीराबाद बैराज',
    type: 'reservoir-inflow',
    river: 'Yamuna',
    basin: 'Ganga',
    sub_basin: 'Yamuna',
    state: 'Delhi',
    district: 'North Delhi',
    latitude: 28.7111,
    longitude: 77.2289,
    elevation_m: 207.0,
    current_level: 206.90,
    warning_level: 206.50,
    danger_level: 207.00,
    hfl: 208.66,
    hfl_date: '2023-07-13',
    inflow_cumec: 8200,
    outflow_cumec: 8100,
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-40',
    station_id: 'YMN-MTR-40',
    code: 'YMN-MTR',
    name: 'Mathura (Prayag Ghat)',
    hindi_name: 'मथुरा (प्रयाग घाट)',
    type: 'river-level',
    river: 'Yamuna',
    basin: 'Ganga',
    sub_basin: 'Yamuna',
    state: 'Uttar Pradesh',
    district: 'Mathura',
    latitude: 27.4924,
    longitude: 77.6737,
    elevation_m: 165.0,
    current_level: 165.20,
    warning_level: 165.20,
    danger_level: 166.00,
    hfl: 167.65,
    hfl_date: '1978-09-10',
    inflow_cumec: 7400,
    outflow_cumec: 7300,
    last_updated: new Date(Date.now() - 6 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-41',
    station_id: 'BRH-NMT-41',
    code: 'BRH-NMT',
    name: 'Neamatighat (Jorhat)',
    hindi_name: 'निमतीघाट (जोरहाट)',
    type: 'river-level',
    river: 'Brahmaputra',
    basin: 'Brahmaputra',
    sub_basin: 'Upper Brahmaputra',
    state: 'Assam',
    district: 'Jorhat',
    latitude: 26.8500,
    longitude: 94.2333,
    elevation_m: 86.0,
    current_level: 86.15,
    warning_level: 85.04,
    danger_level: 85.54,
    hfl: 87.37,
    hfl_date: '1991-07-11',
    inflow_cumec: 32000,
    outflow_cumec: 31800,
    last_updated: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-42',
    station_id: 'BRH-PSG-42',
    code: 'SNG-PSG',
    name: 'Pasighat',
    hindi_name: 'पासीघाट',
    type: 'river-level',
    river: 'Siang',
    basin: 'Brahmaputra',
    sub_basin: 'Siang',
    state: 'Arunachal Pradesh',
    district: 'East Siang',
    latitude: 28.0667,
    longitude: 95.3333,
    elevation_m: 153.0,
    current_level: 152.80,
    warning_level: 153.00,
    danger_level: 153.96,
    hfl: 157.54,
    hfl_date: '2000-06-11',
    inflow_cumec: 14500,
    outflow_cumec: 14300,
    last_updated: new Date(Date.now() - 11 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },
  {
    id: 'stn-43',
    station_id: 'BRK-SLC-43',
    code: 'BRK-SLC',
    name: 'Silchar (Annapurna Ghat)',
    hindi_name: 'सिलचर (अन्नपूर्णा घाट)',
    type: 'river-level',
    river: 'Barak',
    basin: 'Brahmaputra',
    sub_basin: 'Barak',
    state: 'Assam',
    district: 'Cachar',
    latitude: 24.8333,
    longitude: 92.7833,
    elevation_m: 21.0,
    current_level: 20.95,
    warning_level: 19.37,
    danger_level: 19.83,
    hfl: 21.98,
    hfl_date: '2022-06-21',
    inflow_cumec: 6200,
    outflow_cumec: 6100,
    last_updated: new Date(Date.now() - 8 * 60000).toISOString(),
    status: 'Severe',
    trend: 'Rising',
  },
  {
    id: 'stn-44',
    station_id: 'GDV-PLV-44',
    code: 'GDV-PLV',
    name: 'Polavaram Dam Site',
    hindi_name: 'पोलावरम बांध स्थल',
    type: 'reservoir-inflow',
    river: 'Godavari',
    basin: 'Godavari',
    sub_basin: 'Lower Godavari',
    state: 'Andhra Pradesh',
    district: 'Eluru',
    latitude: 17.2583,
    longitude: 81.6500,
    elevation_m: 40.0,
    current_level: 38.60,
    warning_level: 39.00,
    danger_level: 41.50,
    hfl: 43.50,
    hfl_date: '1986-08-16',
    inflow_cumec: 26000,
    outflow_cumec: 25800,
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Rising',
  },
  {
    id: 'stn-45',
    station_id: 'GDV-KLS-45',
    code: 'GDV-KLS',
    name: 'Kaleshwaram (Medigadda Barrage)',
    hindi_name: 'कालेश्वरम (मेडिगड्डा बैराज)',
    type: 'reservoir-inflow',
    river: 'Godavari',
    basin: 'Godavari',
    sub_basin: 'Middle Godavari',
    state: 'Telangana',
    district: 'Jayashankar Bhupalpally',
    latitude: 18.8100,
    longitude: 79.9100,
    elevation_m: 100.0,
    current_level: 99.20,
    warning_level: 99.00,
    danger_level: 100.50,
    hfl: 101.80,
    hfl_date: '2022-07-15',
    inflow_cumec: 21500,
    outflow_cumec: 21400,
    last_updated: new Date(Date.now() - 7 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Steady',
  },
  {
    id: 'stn-46',
    station_id: 'KRS-TGB-46',
    code: 'TGB-HSP',
    name: 'Tungabhadra Dam',
    hindi_name: 'तुंगभद्रा बांध',
    type: 'reservoir-inflow',
    river: 'Tungabhadra',
    basin: 'Krishna',
    sub_basin: 'Tungabhadra',
    state: 'Karnataka',
    district: 'Vijayanagara',
    latitude: 15.2639,
    longitude: 76.3356,
    elevation_m: 490.0,
    current_level: 496.20,
    warning_level: 496.00,
    danger_level: 497.74,
    hfl: 498.50,
    hfl_date: '2009-10-02',
    inflow_cumec: 9800,
    outflow_cumec: 9400,
    last_updated: new Date(Date.now() - 10 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Steady',
  },
  {
    id: 'stn-47',
    station_id: 'NRM-SRS-47',
    code: 'NRM-SRS',
    name: 'Sardar Sarovar Dam',
    hindi_name: 'सरदार सरोवर बांध',
    type: 'reservoir-inflow',
    river: 'Narmada',
    basin: 'Narmada',
    sub_basin: 'Lower Narmada',
    state: 'Gujarat',
    district: 'Narmada',
    latitude: 21.8297,
    longitude: 73.7483,
    elevation_m: 130.0,
    current_level: 136.80,
    warning_level: 136.00,
    danger_level: 138.68,
    hfl: 140.21,
    hfl_date: '2023-09-17',
    inflow_cumec: 24500,
    outflow_cumec: 23900,
    last_updated: new Date(Date.now() - 6 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-48',
    station_id: 'MHN-HRK-48',
    code: 'MHN-HRK',
    name: 'Hirakud Dam',
    hindi_name: 'हीराकुंड बांध',
    type: 'reservoir-inflow',
    river: 'Mahanadi',
    basin: 'Mahanadi',
    sub_basin: 'Middle Mahanadi',
    state: 'Odisha',
    district: 'Sambalpur',
    latitude: 21.5283,
    longitude: 83.8711,
    elevation_m: 190.0,
    current_level: 191.40,
    warning_level: 191.50,
    danger_level: 192.02,
    hfl: 192.65,
    hfl_date: '2001-07-16',
    inflow_cumec: 18400,
    outflow_cumec: 17800,
    last_updated: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },
  {
    id: 'stn-49',
    station_id: 'CVR-KRS-49',
    code: 'CVR-KRS',
    name: 'KRS Dam (Mysuru)',
    hindi_name: 'केआरएस बांध (मैसूरु)',
    type: 'reservoir-inflow',
    river: 'Cauvery',
    basin: 'Cauvery',
    sub_basin: 'Upper Cauvery',
    state: 'Karnataka',
    district: 'Mandya',
    latitude: 12.3814,
    longitude: 76.5731,
    elevation_m: 740.0,
    current_level: 752.10,
    warning_level: 751.50,
    danger_level: 752.86,
    hfl: 753.50,
    hfl_date: '2018-08-15',
    inflow_cumec: 4500,
    outflow_cumec: 4300,
    last_updated: new Date(Date.now() - 8 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Steady',
  },
  {
    id: 'stn-50',
    station_id: 'CVR-BLG-50',
    code: 'CVR-BLG',
    name: 'Biligundlu Inter-State Gaging',
    hindi_name: 'बिलिगुंड्लु अंतर-राज्यीय गेजिंग',
    type: 'river-level',
    river: 'Cauvery',
    basin: 'Cauvery',
    sub_basin: 'Middle Cauvery',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    latitude: 12.1833,
    longitude: 77.7833,
    elevation_m: 235.0,
    current_level: 236.40,
    warning_level: 236.00,
    danger_level: 237.50,
    hfl: 240.10,
    hfl_date: '2022-08-05',
    inflow_cumec: 5600,
    outflow_cumec: 5550,
    last_updated: new Date(Date.now() - 12 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Rising',
  },
  {
    id: 'stn-51',
    station_id: 'IND-JHL-51',
    code: 'JHL-SRN',
    name: 'Srinagar (Ram Munshi Bagh)',
    hindi_name: 'श्रीनगर (राम मुंशी बाग)',
    type: 'river-level',
    river: 'Jhelum',
    basin: 'Indus',
    sub_basin: 'Jhelum',
    state: 'Jammu and Kashmir',
    district: 'Srinagar',
    latitude: 34.0725,
    longitude: 74.8389,
    elevation_m: 1580.0,
    current_level: 1582.40,
    warning_level: 1583.50,
    danger_level: 1585.00,
    hfl: 1588.60,
    hfl_date: '2014-09-07',
    inflow_cumec: 2800,
    outflow_cumec: 2750,
    last_updated: new Date(Date.now() - 14 * 60000).toISOString(),
    status: 'Normal',
    trend: 'Steady',
  },
  {
    id: 'stn-52',
    station_id: 'IND-CHN-52',
    code: 'CHN-AKH',
    name: 'Akhnoor',
    hindi_name: 'अखनूर',
    type: 'river-level',
    river: 'Chenab',
    basin: 'Indus',
    sub_basin: 'Chenab',
    state: 'Jammu and Kashmir',
    district: 'Jammu',
    latitude: 32.8986,
    longitude: 74.7422,
    elevation_m: 305.0,
    current_level: 306.10,
    warning_level: 306.00,
    danger_level: 307.50,
    hfl: 310.20,
    hfl_date: '2014-09-06',
    inflow_cumec: 7800,
    outflow_cumec: 7700,
    last_updated: new Date(Date.now() - 15 * 60000).toISOString(),
    status: 'Above normal',
    trend: 'Falling',
  },
];

/**
 * Generate 48 hours of past hourly observations for a station
 */
export function generateObservationsForStation(station: RawStationDTO): RawObservationDTO[] {
  const current = Number(station.current_level) || 50;
  const now = Date.now();
  const obs: RawObservationDTO[] = [];

  // Generate 48 hourly points ending now
  for (let i = 47; i >= 0; i--) {
    const time = new Date(now - i * 3600000).toISOString();
    // Simulate natural hydrological wave progression
    const wave = Math.sin((48 - i) / 8) * 0.8;
    const progress = (48 - i) / 48;
    // Interpolate from 1.5m below current towards current level
    const baseLevel = (current - 1.2) + (1.2 * progress) + (wave * 0.2);

    obs.push({
      id: `obs-${station.id}-${i}`,
      station_id: station.id,
      timestamp: time,
      water_level: parseFloat(baseLevel.toFixed(2)),
      inflow_cumec: Math.round((Number(station.inflow_cumec) || 5000) * (0.8 + 0.2 * progress)),
      outflow_cumec: Math.round((Number(station.outflow_cumec) || 4900) * (0.8 + 0.18 * progress)),
      rainfall_mm: parseFloat((Math.max(0, Math.sin(i / 4) * 8)).toFixed(1)),
    });
  }

  // Ensure last observation exactly equals current level
  if (obs.length > 0) {
    obs[obs.length - 1].water_level = current;
  }

  return obs;
}

/**
 * Generate 24 hours of future hourly forecasts for a station
 */
export function generateForecastForStation(station: RawStationDTO): RawForecastDTO[] {
  const current = Number(station.current_level) || 50;
  const warning = Number(station.warning_level) || 48;
  const danger = Number(station.danger_level) || 51;
  const hfl = Number(station.hfl) || 53;

  const now = Date.now();
  const forecasts: RawForecastDTO[] = [];
  const isRising = station.trend === 'Rising';

  for (let i = 1; i <= 24; i++) {
    const forecastTime = new Date(now + i * 3600000).toISOString();
    const delta = isRising ? (i * 0.04) + Math.sin(i / 3) * 0.08 : -(i * 0.03);
    const predicted = current + delta;
    const errorMargin = 0.05 + (i * 0.015);

    let severity = 'Normal';
    if (predicted >= hfl) severity = 'Extreme';
    else if (predicted >= danger) severity = 'Severe';
    else if (predicted >= warning) severity = 'Above normal';

    forecasts.push({
      id: `fc-${station.id}-${i}`,
      station_id: station.id,
      forecast_time: forecastTime,
      predicted_level: parseFloat(predicted.toFixed(2)),
      predicted_inflow: Math.round((Number(station.inflow_cumec) || 5000) * (1 + (isRising ? 0.02 * i : -0.01 * i))),
      confidence_lower: parseFloat((predicted - errorMargin).toFixed(2)),
      confidence_upper: parseFloat((predicted + errorMargin).toFixed(2)),
      trend: isRising ? 'Rising' : 'Falling',
      severity,
    });
  }

  return forecasts;
}

export const MOCK_BULLETINS: RawBulletinDTO[] = [
  {
    id: 'bul-01',
    bulletin_no: 'CWC/FF/2026/089',
    title: 'Extreme Flood Inundation Warning for Dibrugarh & Upper Brahmaputra Reach',
    title_hi: 'डिब्रूगढ़ एवं ऊपरी ब्रह्मपुत्र क्षेत्र हेतु अत्यधिक बाढ़ चेतावनी',
    date_time: new Date(Date.now() - 45 * 60000).toISOString(),
    summary: 'River Brahmaputra at Dibrugarh has surpassed its historical Highest Flood Level (106.02m) by 10cm following relentless catchment rainfall in Arunachal Pradesh. Severe flood situation in Kamrup and Sonitpur districts. Immediate evacuation protocols active.',
    summary_hi: 'अरुणाचल प्रदेश के जलग्रहण क्षेत्रों में भारी वर्षा के उपरांत डिब्रूगढ़ में ब्रह्मपुत्र नदी ने अपने ऐतिहासिक उच्चतम बाढ़ स्तर (106.02 मी) को पार कर लिया है। कामरूप एवं सोनितपुर में स्थिति गंभीर है।',
    severity: 'Extreme',
    affected_basins: ['Brahmaputra'],
    affected_states: ['Assam', 'Arunachal Pradesh'],
    key_stations_affected: ['Dibrugarh', 'Guwahati', 'Tezpur', 'Dhubri'],
  },
  {
    id: 'bul-02',
    bulletin_no: 'CWC/FF/2026/088',
    title: 'Severe Flood Alert: River Krishna at Prakasam Barrage Exceeds Historical Peak',
    title_hi: 'गंभीर बाढ़ चेतावनी: प्रकाशम बैराज पर कृष्णा नदी ऐतिहासिक उच्चतम स्तर से ऊपर',
    date_time: new Date(Date.now() - 120 * 60000).toISOString(),
    summary: 'Due to huge outflows from upstream Srisailam and Nagarjuna Sagar reservoirs, water level at Prakasam Barrage (Vijayawada) is currently at 18.20m, exceeding danger mark with outflow at 29,500 cumec. Krishna and Guntur low-lying mandals alerted.',
    summary_hi: 'श्रीशैलम एवं नागार्जुन सागर से भारी जल निकासी के कारण विजयवाड़ा प्रकाशम बैराज पर जलस्तर 18.20 मी पहुंच गया है। निचले इलाकों में रेड अलर्ट जारी।',
    severity: 'Extreme',
    affected_basins: ['Krishna'],
    affected_states: ['Andhra Pradesh', 'Telangana'],
    key_stations_affected: ['Prakasam Barrage', 'Srisailam Dam'],
  },
  {
    id: 'bul-03',
    bulletin_no: 'CWC/FF/2026/087',
    title: 'Severe Flood Advisory: Middle Ganga Reach at Patna and Farakka',
    title_hi: 'गंभीर बाढ़ परामर्श: मध्य गंगा क्षेत्र - पटना एवं फरक्का',
    date_time: new Date(Date.now() - 240 * 60000).toISOString(),
    summary: 'River Ganga at Patna (Digha Ghat) is flowing 0.37m above its Danger Level with a rising trend of 2cm/hr. Farakka Barrage is discharging 48,200 cumec to balance reservoir pondage.',
    summary_hi: 'पटना (दीघा घाट) पर गंगा नदी खतरे के निशान से 0.37 मी ऊपर बह रही है एवं 2 सेमी/घंटे की दर से बढ़ रही है। फरक्का बैराज पर भारी जल निकासी जारी।',
    severity: 'Severe',
    affected_basins: ['Ganga'],
    affected_states: ['Bihar', 'West Bengal', 'Uttar Pradesh'],
    key_stations_affected: ['Patna', 'Varanasi', 'Farakka Barrage'],
  },
  {
    id: 'bul-04',
    bulletin_no: 'CWC/FF/2026/086',
    title: 'Flood Advisory: River Yamuna at Old Railway Bridge Delhi',
    title_hi: 'बाढ़ परामर्श: दिल्ली पुराना रेलवे पुल पर यमुना नदी',
    date_time: new Date(Date.now() - 360 * 60000).toISOString(),
    summary: 'River Yamuna at Delhi Old Railway Bridge crossed its Danger Mark of 205.33m and is at 206.15m due to discharge from Hathnikund Barrage. Flood plain settlements evacuated.',
    summary_hi: 'हथिनीकुंड बैराज से पानी छोड़े जाने के कारण दिल्ली पुराने रेलवे पुल पर यमुना नदी खतरे के निशान 205.33 मी को पार कर 206.15 मी पर बह रही है।',
    severity: 'Severe',
    affected_basins: ['Ganga'],
    affected_states: ['Delhi', 'Haryana', 'Uttar Pradesh'],
    key_stations_affected: ['Delhi (Old Railway Bridge)', 'Mathura'],
  },
  {
    id: 'bul-05',
    bulletin_no: 'CWC/FF/2026/085',
    title: 'Reservoir Inflow Advisory: Sardar Sarovar & Narmada Reach',
    title_hi: 'जलाशय अंतर्वाह परामर्श: सरदार सरोवर एवं नर्मदा क्षेत्र',
    date_time: new Date(Date.now() - 480 * 60000).toISOString(),
    summary: 'Inflow of 22,400 cumec recorded at Sardar Sarovar Dam. Downstream Garudeshwar is flowing at Severe stage. Bharuch district disaster authorities deployed NDRF teams.',
    summary_hi: 'सरदार सरोवर बांध पर 22,400 क्यूमेक का अंतर्वाह दर्ज। गरुड़ेश्वर में गंभीर स्थिति, भरूच में एनडीआरएफ तैनात।',
    severity: 'Warning',
    affected_basins: ['Narmada'],
    affected_states: ['Gujarat', 'Madhya Pradesh'],
    key_stations_affected: ['Garudeshwar', 'Sardar Sarovar Dam Inflow'],
  },
];
